### PR TITLE
WIP: ncurses

### PR DESCRIPTION
**Pull request by dragonfax**

### CODE REVIEW

**Comment by dragonfax** [comment]
woops. meant to create this on my fork. not yours. sorry.

**Comment by zachlatta** [comment]
No worries! This is awesome though.

On Tue, Mar 22, 2016 at 9:46 PM, Jason Stillwell <notifications@github.com>
wrote:

> woops. meant to create this on my fork. not yours. sorry.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/sshtron/pull/16#issuecomment-200173789>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by dragonfax** [comment]
Meh, still hitting concurrency issues. Not sure if its in my sloppy code, or just something that can't be fixed in ncurses.

**Comment by dragonfax** [comment]
I think ncurses with multiple screens just isn't tested well as no one uses it.

**Pull request closed without merging**
