### PR TITLE
 Add win streak rainbows to the trails. 

### PR DESCRIPTION
**Pull request by mbjorge**
Whenever a player collides with another player's
trail, the surviving player gets the dead player's
color added to their trail rainbow, indicating their
win streak.

When a player dies, their streak ends and their trail
starts back again as a solid color.

Issue #24

### CODE REVIEW

**Comment by mbjorge** [comment]
This is some of the first go code I've written, so if it needs adjutsing, let me know

**Comment by mbjorge** [comment]
I tested locally manually with 2 clients. I had a win streak with several colors in it and checked that the colors correctly reset upon death.

**Comment by zachlatta** [comment]
Ahh, this is so awesome. I'm out to dinner now and will try to review and merge later tonight, latest tomorrow eve.
		
		

		
	




On Sat, Feb 10, 2018 at 5:41 PM -0800, "Michael Bjorge" <notifications@github.com> wrote:












I tested locally manually with 2 clients. I had a win streak with several colors in it and checked that the colors correctly reset upon death.

**Comment by alyyousuf7** [comment]
This is how it looks:

sshtron

**Comment by alyyousuf7** [comment]
Played it with a couple of colleagues, here are some longer chained screenshots:

sshtron-confusion
Over here, it gets pretty easy to confuse your snake with the other one.

sshtron-color-not-present
Not an issue but Magenta left the game but it's traces are still on the green snake.

sshtron-confusion-2
It took me sometime to realize that there are 3 snakes and not 2.

**A suggestion from a colleague**
It would look better if only the part which collided changes its color instead of a pattern.
For example, if a red snake has 8-length chain and green dies by colliding red snake on the 6th chain, only that chain gets a green color. Here's an attempt to illustrate it:

```
Red Snake
 |
 |
 |<------- Green Snake
 |    Only this chain of the red snake gets a green color.
 |
 |
 |
 |
\_/
```

**Comment by zachlatta** [comment]
@alyyousuf7: think you could take point on reviewing this change / getting some variant of it in? really meant to properly review this last night, but am chronically underestimating my availability :-(. think you'll be much more capable.

**Comment by mbjorge** [comment]
Good point about it being hard to differentiate the trails. I have updated the PR to try the suggestion to only change the color for the segment that was collided with. Let me know what you think of that

**Comment by alyyousuf7** [comment]
It looks functionally good to me.

@mbjorge, can you squash the first and the third commit?

**Comment by zachlatta** [comment]
Going to just go ahead and merge to get this in :-).

**Pull request merged**
