### PR TITLE
Reformats the code

### PR DESCRIPTION
**Pull request by TheThirdOne**
Changes:
  - The game manager and session  definitions are now in a separate file.
  - Some unnecessary channels are replaced with function calls or inlined. 
    - Hub is completely deleted
  - Some features are moved from Session to Player
  - Tiles are removed completely

### CODE REVIEW

**Comment by zachlatta** [comment]
I remember we talked on Slack about having you do an extensive test of
this. I have a ton on my plate right now and I don't think I'll have time
to do an in-depth review of this.

Any updates on that test?

On Tue, Mar 15, 2016 at 12:19 AM, Benjamin Landers <notifications@github.com
> wrote:

> Changes:
>
>    - The game manager and session definitions are now in a separate file.
>    - Some unnecessary channels are replaced with function calls or
>    inlined.
>       - Hub is completely deleted
>    - Some features are moved from Session to Player
>    - Tiles are removed completely
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/zachlatta/sshtron/pull/15
> Commit Summary
>
>    - Reformats and removes some dead code
>    - Merge origin/master
>
> File Changes
>
>    - *M* game.go
>    <https://github.com/zachlatta/sshtron/pull/15/files#diff-0> (354)
>    - *A* helper.go
>    <https://github.com/zachlatta/sshtron/pull/15/files#diff-1> (141)
>    - *M* main.go
>    <https://github.com/zachlatta/sshtron/pull/15/files#diff-2> (8)
>
> Patch Links:
>
>    - https://github.com/zachlatta/sshtron/pull/15.patch
>    - https://github.com/zachlatta/sshtron/pull/15.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zachlatta/sshtron/pull/15
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by TheThirdOne** [comment]
Oh, I totally forgot about this. I still don't have a great way to test multiplayer though. I can work on testing it though.

**Comment by zachlatta** [comment]
Let me know – would love to get this merged.

On Wed, Jun 15, 2016 at 10:57 PM, Benjamin Landers <notifications@github.com
> wrote:

> Oh, I totally forgot about this. I still don't have a great way to test
> multiplayer though. I can work on testing it though.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zachlatta/sshtron/pull/15#issuecomment-226394967>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-G1nTQA1TOxX1Y-PlQwk2j9qCvmgks5qMOXhgaJpZM4Hww-u>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Closing due to lack of activity.

**Comment by zachlatta** [comment]
Happy to re-open if you're still interested in getting this merged.

**Pull request closed without merging**
